spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_db
    username: db
    password: hr
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true