spring:
  datasource:
    url: jdbc:h2:mem:hr_db;DB_CLOSE_DELAY=-1
    username: db
    password: hr
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true