version: '2'

services:
  hr_db:
    image: postgres:10.4-alpine
    ports:
    - 5432:5432
    volumes:
    - hr_db:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=hr
    - POSTGRES_USER=db
    - POSTGRES_DB=hr_db
volumes:
  hr_db: